# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
    
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter test
    
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run:  docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gui . --network=host


      - name: Push to docker registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gui
          #start_on_k8:
          #name: start on k8 
          #runs-on: self-hosted
          #steps:
      - name: login vsphere kubectl 
        run: echo "/root/K8s_setup_Yuki.sh" > /root/.signature; cat /root/.signature
      - name: remove old dep 
        run: echo "kubectl delete deployment gui" > /root/.signature; cat /root/.signature
      - name: create new dep 
        run: echo "kubectl create deployment gui --image yukiiso/gui" > /root/.signature; cat /root/.signature
